// <auto-generated />
using System;
using LMS_ServerAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS_ServerAPI.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20241226184604_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookAge", b =>
                {
                    b.Property<int>("Book")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.HasKey("Book", "Age");

                    b.HasIndex("Age");

                    b.ToTable("BookAge", (string)null);
                });

            modelBuilder.Entity("BookAuthor", b =>
                {
                    b.Property<int>("Author")
                        .HasColumnType("int");

                    b.Property<int>("Book")
                        .HasColumnType("int");

                    b.HasKey("Author", "Book");

                    b.HasIndex("Book");

                    b.ToTable("BookAuthor", (string)null);
                });

            modelBuilder.Entity("BookCategory", b =>
                {
                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Book")
                        .HasColumnType("int");

                    b.HasKey("Category", "Book");

                    b.HasIndex("Book");

                    b.ToTable("BookCategory", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(511)
                        .IsUnicode(false)
                        .HasColumnType("varchar(511)");

                    b.Property<int?>("Street")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Street");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Age", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FromAge")
                        .HasColumnType("int");

                    b.Property<int?>("ToAge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Age", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nation")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Author", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Image")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("ISBN");

                    b.Property<string>("Language")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .HasMaxLength(511)
                        .HasColumnType("nvarchar(511)");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int?>("PublishYear")
                        .HasColumnType("int");

                    b.Property<int?>("Publisher")
                        .HasColumnType("int");

                    b.Property<int?>("Series")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Vendor")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Publisher");

                    b.HasIndex("Series");

                    b.HasIndex("Vendor");

                    b.ToTable("Book", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.BookImg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Book")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("Book");

                    b.ToTable("BookImg", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.BookInBranch", b =>
                {
                    b.Property<int>("Library")
                        .HasColumnType("int");

                    b.Property<int>("Book")
                        .HasColumnType("int");

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CallNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Library", "Book");

                    b.HasIndex("Book");

                    b.ToTable("BookInBranch", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.BookLoan", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Book")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("IsReturned")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Book");

                    b.HasIndex("User");

                    b.ToTable("BookLoan", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Parent")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(551)
                        .IsUnicode(false)
                        .HasColumnType("varchar(551)");

                    b.HasKey("Id");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("City")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(551)
                        .IsUnicode(false)
                        .HasColumnType("varchar(551)");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.ToTable("District", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Address")
                        .HasColumnType("int");

                    b.Property<int?>("Manager")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<TimeOnly?>("OpenFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("OpenTo")
                        .HasColumnType("time");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.ToTable("Library", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Parent")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Parent");

                    b.ToTable("Publisher", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Name")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Ward")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ward");

                    b.ToTable("Street", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("Address")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Fullname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Pid")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PID");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Library")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("Library");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.UserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(551)
                        .HasColumnType("nvarchar(551)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vendor", (string)null);
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("District")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(511)
                        .IsUnicode(false)
                        .HasColumnType("varchar(511)");

                    b.HasKey("Id");

                    b.HasIndex("District");

                    b.ToTable("Ward", (string)null);
                });

            modelBuilder.Entity("BookAge", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Age", null)
                        .WithMany()
                        .HasForeignKey("Age")
                        .IsRequired()
                        .HasConstraintName("FK_BookAge_Age");

                    b.HasOne("LMS_ServerAPI.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("Book")
                        .IsRequired()
                        .HasConstraintName("FK_BookAge_Book");
                });

            modelBuilder.Entity("BookAuthor", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("Author")
                        .IsRequired()
                        .HasConstraintName("FK_BookAuthor_Author");

                    b.HasOne("LMS_ServerAPI.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("Book")
                        .IsRequired()
                        .HasConstraintName("FK_BookAuthor_Book");
                });

            modelBuilder.Entity("BookCategory", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("Book")
                        .IsRequired()
                        .HasConstraintName("FK_BookCategory_Book");

                    b.HasOne("LMS_ServerAPI.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("Category")
                        .IsRequired()
                        .HasConstraintName("FK_BookCategory_Category");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Address", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Street", "StreetNavigation")
                        .WithMany("Addresses")
                        .HasForeignKey("Street")
                        .HasConstraintName("FK_Address_Street");

                    b.Navigation("StreetNavigation");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Book", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Publisher", "PublisherNavigation")
                        .WithMany("Books")
                        .HasForeignKey("Publisher")
                        .HasConstraintName("FK_Book_Publisher");

                    b.HasOne("LMS_ServerAPI.Models.Series", "SeriesNavigation")
                        .WithMany("Books")
                        .HasForeignKey("Series")
                        .HasConstraintName("FK_Book_Series");

                    b.HasOne("LMS_ServerAPI.Models.Vendor", "VendorNavigation")
                        .WithMany("Books")
                        .HasForeignKey("Vendor")
                        .HasConstraintName("FK_Book_Vendor");

                    b.Navigation("PublisherNavigation");

                    b.Navigation("SeriesNavigation");

                    b.Navigation("VendorNavigation");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.BookImg", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Book", "BookNavigation")
                        .WithMany("BookImgs")
                        .HasForeignKey("Book")
                        .IsRequired()
                        .HasConstraintName("FK_BookImg_Book");

                    b.Navigation("BookNavigation");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.BookInBranch", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Book", "BookNavigation")
                        .WithMany("BookInBranches")
                        .HasForeignKey("Book")
                        .IsRequired()
                        .HasConstraintName("FK_BookInBranch_Book");

                    b.HasOne("LMS_ServerAPI.Models.Library", "LibraryNavigation")
                        .WithMany("BookInBranches")
                        .HasForeignKey("Library")
                        .IsRequired()
                        .HasConstraintName("FK_BookInBranch_Library");

                    b.Navigation("BookNavigation");

                    b.Navigation("LibraryNavigation");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.BookLoan", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Book", "BookNavigation")
                        .WithMany("BookLoans")
                        .HasForeignKey("Book")
                        .IsRequired()
                        .HasConstraintName("FK_BookLoan_Book");

                    b.HasOne("LMS_ServerAPI.Models.User", "UserNavigation")
                        .WithMany("BookLoans")
                        .HasForeignKey("User")
                        .IsRequired()
                        .HasConstraintName("FK_BookLoan_User");

                    b.Navigation("BookNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.District", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.City", "CityNavigation")
                        .WithMany("Districts")
                        .HasForeignKey("City")
                        .HasConstraintName("FK_District_City");

                    b.Navigation("CityNavigation");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Library", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Address", "AddressNavigation")
                        .WithMany("Libraries")
                        .HasForeignKey("Address")
                        .HasConstraintName("FK_Library_Address");

                    b.Navigation("AddressNavigation");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Publisher", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Publisher", "ParentNavigation")
                        .WithMany("InverseParentNavigation")
                        .HasForeignKey("Parent")
                        .HasConstraintName("FK_Publisher_Publisher");

                    b.Navigation("ParentNavigation");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.RoleClaim", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoleClaims_RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Street", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Ward", "WardNavigation")
                        .WithMany("Streets")
                        .HasForeignKey("Ward")
                        .HasConstraintName("FK_Street_Ward");

                    b.Navigation("WardNavigation");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.User", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Address", "AddressNavigation")
                        .WithMany("Users")
                        .HasForeignKey("Address")
                        .HasConstraintName("FK_Users_Address");

                    b.Navigation("AddressNavigation");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.UserClaim", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserClaims_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.UserLogin", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.User", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserLogins_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.UserRole", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.Library", "LibraryNavigation")
                        .WithMany("UserRoles")
                        .HasForeignKey("Library")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_UserRoles_Library");

                    b.HasOne("LMS_ServerAPI.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_RoleId");

                    b.HasOne("LMS_ServerAPI.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_UserId");

                    b.Navigation("LibraryNavigation");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.UserToken", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserTokens_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Ward", b =>
                {
                    b.HasOne("LMS_ServerAPI.Models.District", "DistrictNavigation")
                        .WithMany("Wards")
                        .HasForeignKey("District")
                        .HasConstraintName("FK_Ward_District");

                    b.Navigation("DistrictNavigation");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Address", b =>
                {
                    b.Navigation("Libraries");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Book", b =>
                {
                    b.Navigation("BookImgs");

                    b.Navigation("BookInBranches");

                    b.Navigation("BookLoans");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.District", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Library", b =>
                {
                    b.Navigation("BookInBranches");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Publisher", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("InverseParentNavigation");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Series", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Street", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.User", b =>
                {
                    b.Navigation("BookLoans");

                    b.Navigation("UserClaims");

                    b.Navigation("UserLogins");

                    b.Navigation("UserRoles");

                    b.Navigation("UserTokens");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Vendor", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LMS_ServerAPI.Models.Ward", b =>
                {
                    b.Navigation("Streets");
                });
#pragma warning restore 612, 618
        }
    }
}
